version: '3.8'
services:
  rstudio:
    environment:
      - DISABLE_AUTH=true
      - USER=rstudio
      - PASSWORD=qwerty
      - MY_VAR=1
    image: "rocker/verse:latest"
    ports:
     - 8787:8787
    volumes:
     - ./rstudio_data:/home/rstudio
     
     
     
